env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:

  - id: nowin
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/huoxue1/tdlib/conf.VERSION=v{{.Version}} -X github.com/huoxue1/tdlib/conf.VERSION=v{{.Commit}}
  - id: win
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - windows
    goarch:
      - 386
      - amd64
    goarm:
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/huoxue1/tdlib/conf.VERSION=v{{.Version}} -X github.com/huoxue1/tdlib/conf.VERSION=v{{.Commit}}
  - id: docker
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/huoxue1/tdlib/conf.VERSION=v{{.Version}} -X github.com/huoxue1/tdlib/conf.VERSION=v{{.Commit}}
  - id: ci
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    binary: {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/huoxue1/tdlib/conf.VERSION=v{{.Version}} -X github.com/huoxue1/tdlib/conf.VERSION=v{{.Commit}}

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - fix typo
      - Merge pull request
      - Merge branch
      - Merge remote-tracking
      - go mod tidy

archives:
  - id: binary
    builds:
      - win
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: binary
  - id: nowin
    builds:
      - nowin
      - win
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip


#nfpms:
#  - license: AGPL 3.0
#    homepage: https://github.com/huoxue1/tdlib
#    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
#    formats:
#      - deb
#      - rpm
#    maintainer: huoxue1
#    builds:
#      - nowin
#      - win