version: "3.5"
services:
  tdlib:
    image: huoxue1/tdlib:latest
    # 容器名
    container_name: tdlib
    environment:
    # 时区
      - TZ=Asia/Shanghai
    # 配置文件路径
    volumes:
      - ${pwd}/tdlib:/tdlib/
    # 映射端口
#    ports:
#      - 8080:8080
    restart: unless-stopped